name: Testing stuff2334

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(join(' ', github.event.commits.*.message), 'hamburger')}}
    steps:
      - uses: actions/checkout@v2
      - name: Debug condition
        run: |
          echo "Commit messages:"
          echo "${{ toJson(github.event.commits.*.message) }}"
          echo "Condition result: ${{ contains(join(' ', github.event.commits.*.message), 'hamburger') }}"
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
